### ISSUE TITLE
kien/ctrlp.vim is old.

### ISSUE THREAD

**Issue by get-me-power** [Hilenet/dotfiles#1]
`kien/ctrlp.vim` is not currently maintained, so it is recommended that you use `ctrlpvim/ctrlp.vim`.

`ctrlpvim/ctrlp.vim` is fork from `kien/ctrlp.vim` 

## Referenve
> https://github.com/Hilenet/dotfiles/blob/master/.vim/dein.toml#L36
> https://github.com/ctrlpvim/ctrlp.vim/

If you don't need this pull request, feel free to close it. 🙇

**Comment by hilenet** [comment]
This repo is completely outdated and now using [`junegunn/fzf.vim`](https://github.com/junegunn/fzf.vim) (which you recommended!).
Would update it again sometime, so please check it out when you feel like it.

I'm glad you're reviewing it, thanks.

**Comment by get-me-power** [comment]
@Hilenet 
Thanks!!
